using System.Collections.Immutable;
using System.Text;
using Atom.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Atom.SourceGeneration.PipeWire;

/// <summary>
/// Инкрементальный генератор C# констант из SPA заголовочных файлов PipeWire.
/// Читает .h файлы добавленные как AdditionalFiles с префиксом "spa_" и генерирует
/// статический класс <c>SpaConstants</c> с <c>internal const uint</c> полями.
/// </summary>
[Generator]
public sealed class SpaConstantsSourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var headers = context.AdditionalTextsProvider
            .Where(static file => Path.GetFileName(file.Path)
                .StartsWith("spa_", StringComparison.OrdinalIgnoreCase)
                && file.Path.EndsWith(".h", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(headers.Collect(), Execute);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<AdditionalText> headers)
    {
        if (headers.IsDefaultOrEmpty)
        {
            return;
        }

        var sb = new ValueStringBuilder(4096);

        AppendHeader(ref sb);
        AppendEntries(ref sb, context, headers);

        sb.AppendLine("}");

        var source = sb.ToString();
        sb.Dispose();

        context.AddSource("SpaConstants.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static void AppendHeader(ref ValueStringBuilder sb)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Сгенерировано Atom.SourceGeneration из SPA заголовочных файлов PipeWire.");
        sb.AppendLine("// Не редактировать вручную — обновите .h файлы и пересоберите проект.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Atom.Media.Audio.Backends.PipeWire;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Константы SPA (Simple Plugin API) из заголовочных файлов PipeWire.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class SpaConstants");
        sb.AppendLine("{");
    }

    private static void AppendEntries(ref ValueStringBuilder sb, SourceProductionContext context,
        ImmutableArray<AdditionalText> headers)
    {
        var sortedHeaders = headers
            .OrderBy(static h => Path.GetFileName(h.Path), StringComparer.OrdinalIgnoreCase)
            .ToArray();

        for (var i = 0; i < sortedHeaders.Length; i++)
        {
            var header = sortedHeaders[i];
            var text = header.GetText(context.CancellationToken)?.ToString();
            if (string.IsNullOrEmpty(text))
            {
                continue;
            }

            var (enumName, entries) = SpaHeaderParser.Parse(text!);
            if (entries.Count == 0)
            {
                continue;
            }

            var fileName = Path.GetFileName(header.Path);
            sb.Append($"    // {enumName} ({fileName})").AppendLine();

            foreach (var entry in entries)
            {
                sb.Append($"    internal const uint {entry.Name} = 0x{entry.Value:X};").AppendLine();
            }

            if (i < sortedHeaders.Length - 1)
            {
                sb.AppendLine();
            }
        }
    }
}
