using System.Runtime.InteropServices;

namespace Atom.Media;

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct CodecContext
{
    public readonly void* av_class;
    public int log_level_offset;
    public int codec_type;
    public AVCodec* codec;
    public MediaCodec Kind;
    public uint codec_tag;
    public void* priv_data;
    public void* @internal;
    public void* opaque;
    public long bit_rate;
    public int flags;
    public int flags2;
    public byte* extraData;
    public int extraData_size;
    public Ratio time_base;
    public Ratio pkt_timeBase;
    public Ratio framerate;
    [Obsolete] public int ticks_per_frame;
    public int delay;
    public int width;
    public int height;
    public int coded_width;
    public int coded_height;
    public Ratio sample_aspect_ratio;
    public PixelFormat Format;
    public int sw_pix_fmt;
    public int color_primaries;
    public int color_trc;
    public int colorSpace;
    public int color_range;
    public int chroma_sample_location;
    public int field_order;
    public int refs;
    public int has_b_frames;
    public int slice_flags;
    public void* callback1;
    public void* callback2;
    public int max_b_frames;
    public float b_quant_factor;
    public float b_quant_offset;
    public float i_quant_factor;
    public float i_quant_offset;
    public float lumi_masking;
    public float temporal_cplx_masking;
    public float spatial_cplx_masking;
    public float p_masking;
    public float dark_masking;
    public int nsse_weight;
    public int me_cmp;
    public int me_sub_cmp;
    public int mb_cmp;
    public int ildct_cmp;
    public int dia_size;
    public int last_predictor_count;
    public int me_pre_cmp;
    public int pre_dia_size;
    public int me_subpel_quality;
    public int me_range;
    public int mb_decision;
    public ushort* intra_matrix;
    public ushort* inter_matrix;
    public ushort* chroma_intra_matrix;
    public int intra_dc_precision;
    public int mb_lmin;
    public int mb_lmax;
    public int bidir_refine;
    public int keyint_min;
    public int gop_size;
    public int mv0_threshold;
    public int slices;
    public int sample_rate;
    public SampleFormat SampleFormat;
    public ChannelLayout ChannelLayout;
    public int frame_size;
    public int block_align;
    public int cutoff;
    public int audio_service_type;
    public int request_sample_fmt;
    public int initial_padding;
    public int trailing_padding;
    public int seek_preroll;
    public void* callback3;
    public int bit_rate_tolerance;
    public int global_quality;
    public int compression_level;
    public float qcompress;
    public float qblur;
    public int qmin;
    public int qmax;
    public int max_qdiff;
    public int rc_buffer_size;
    public int rc_override_count;
    public void* rc_override;
    public long rc_max_rate;
    public long rc_min_rate;
    public float rc_max_available_vbv_use;
    public float rc_min_vbv_overflow_use;
    public int rc_initial_buffer_occupancy;
    public int trellis;
}