export const bridgeCommands = [
    'Navigate',
    'Reload',
    'ExecuteScript',
    'FindElement',
    'FindElements',
    'GetElementProperty',
    'ResolveElementScreenPoint',
    'DescribeElement',
    'FocusElement',
    'ScrollElementIntoView',
    'GetUrl',
    'GetTitle',
    'GetContent',
    'CaptureScreenshot',
    'SetCookie',
    'GetCookies',
    'DeleteCookies',
    'WaitForElement',
    'WaitForNavigation',
    'InterceptRequest',
    'SubscribeCallback',
    'UnSubscribeCallback',
    'CloseTab',
    'OpenTab',
    'OpenWindow',
    'CloseWindow',
    'ActivateTab',
    'ActivateWindow',
    'GetWindowBounds',
    'SetTabContext',
    'ExecuteScriptInFrames',
    'DebugPortStatus',
    'CheckShadowRoot',
] as const;

export type BridgeCommand = (typeof bridgeCommands)[number];