using System.Collections.ObjectModel;
using System.Text.Json;
using System.Text.Json.Serialization;
using Atom.Web.Browsing.BiDi.Bluetooth;
using Atom.Web.Browsing.BiDi.Browser;
using Atom.Web.Browsing.BiDi.BrowsingContext;
using Atom.Web.Browsing.BiDi.Input;
using Atom.Web.Browsing.BiDi.Log;
using Atom.Web.Browsing.BiDi.Network;
using Atom.Web.Browsing.BiDi.Permissions;
using Atom.Web.Browsing.BiDi.Protocol;
using Atom.Web.Browsing.BiDi.Script;
using Atom.Web.Browsing.BiDi.Session;
using Atom.Web.Browsing.BiDi.Storage;
using Atom.Web.Browsing.BiDi.WebExtension;

namespace Atom.Web.Browsing.BiDi;

/// <summary>
/// Представляет контекст сериализации.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    GenerationMode = JsonSourceGenerationMode.Metadata,
    WriteIndented = true
)]
[JsonSerializable(typeof(byte))]
[JsonSerializable(typeof(sbyte))]
[JsonSerializable(typeof(short))]
[JsonSerializable(typeof(ushort))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(uint))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(ulong))]
[JsonSerializable(typeof(float))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(decimal))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(Guid))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(IDictionary<string, object?>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, object?>), TypeInfoPropertyName = "Form")]
[JsonSerializable(typeof(ReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(Target))]
[JsonSerializable(typeof(RealmTarget))]
[JsonSerializable(typeof(ContextTarget))]
[JsonSerializable(typeof(EvaluateResultSuccess))]
[JsonSerializable(typeof(EvaluateResultException))]
[JsonSerializable(typeof(RegularExpressionValue))]
[JsonSerializable(typeof(NodeProperties))]
[JsonSerializable(typeof(WindowProxyProperties))]
[JsonSerializable(typeof(RealmType))]
[JsonSerializable(typeof(ProxyConfiguration))]
[JsonSerializable(typeof(ProxyType))]
[JsonSerializable(typeof(AutoDetectProxyConfiguration))]
[JsonSerializable(typeof(DirectProxyConfiguration))]
[JsonSerializable(typeof(ManualProxyConfiguration))]
[JsonSerializable(typeof(PacProxyConfiguration))]
[JsonSerializable(typeof(SystemProxyConfiguration))]
[JsonSerializable(typeof(RemoteValue))]
[JsonSerializable(typeof(LogLevel))]
[JsonSerializable(typeof(Source))]
[JsonSerializable(typeof(StackTrace))]
[JsonSerializable(typeof(CommandParameters))]
[JsonSerializable(typeof(Command))]
[JsonSerializable(typeof(CommandResponseMessage))]
[JsonSerializable(typeof(ErrorResponseMessage))]
[JsonSerializable(typeof(EventMessage))]
[JsonSerializable(typeof(RequestDeviceInfo))]
[JsonSerializable(typeof(EventMessage<RequestDevicePromptUpdatedEventArgs>))]
[JsonSerializable(typeof(ClientWindowInfo))]
[JsonSerializable(typeof(CommandResponseMessage<CreateUserContextCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<GetClientWindowsCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<GetUserContextsCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<SetClientWindowStateCommandResult>))]
[JsonSerializable(typeof(EventMessage<BrowsingContextInfo>))]
[JsonSerializable(typeof(CommandResponseMessage<CaptureScreenshotCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<CreateCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<GetTreeCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<NavigationResult>))]
[JsonSerializable(typeof(CommandResponseMessage<PrintCommandResult>))]
[JsonSerializable(typeof(EventMessage<LogEntry>))]
[JsonSerializable(typeof(CommandResponseMessage<AddInterceptCommandResult>))]
[JsonSerializable(typeof(AuthChallenge))]
[JsonSerializable(typeof(EventMessage<AuthRequiredEventArgs>))]
[JsonSerializable(typeof(BaseNetworkEventArgs))]
[JsonSerializable(typeof(EventMessage<BeforeRequestSentEventArgs>))]
[JsonSerializable(typeof(Cookie))]
[JsonSerializable(typeof(FetchTimingInfo))]
[JsonSerializable(typeof(Header))]
[JsonSerializable(typeof(Initiator))]
[JsonSerializable(typeof(RequestData))]
[JsonSerializable(typeof(EventMessage<ResponseCompletedEventArgs>))]
[JsonSerializable(typeof(ResponseContent))]
[JsonSerializable(typeof(EventMessage<ResponseStartedEventArgs>))]
[JsonSerializable(typeof(CommandResponseMessage<AddPreloadScriptCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<EvaluateResult>))]
[JsonSerializable(typeof(CommandResponseMessage<GetRealmsCommandResult>))]
[JsonSerializable(typeof(CapabilitiesResult))]
[JsonSerializable(typeof(CommandResponseMessage<NewCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<StatusCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<DeleteCookiesCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<GetCookiesCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<SetCookieCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<InstallCommandResult>))]
[JsonSerializable(typeof(ExtensionPath))]
[JsonSerializable(typeof(ExtensionArchivePath))]
[JsonSerializable(typeof(ExtensionBase64Encoded))]
[JsonSerializable(typeof(InstallCommandParameters))]
[JsonSerializable(typeof(UninstallCommandParameters))]
[JsonSerializable(typeof(EventMessage<RealmDestroyedEventArgs>))]
[JsonSerializable(typeof(EventMessage<MessageEventArgs>))]
[JsonSerializable(typeof(EventMessage<NavigationEventArgs>))]
[JsonSerializable(typeof(EventMessage<HistoryUpdatedEventArgs>))]
[JsonSerializable(typeof(EventMessage<UserPromptClosedEventArgs>))]
[JsonSerializable(typeof(EventMessage<UserPromptOpenedEventArgs>))]
[JsonSerializable(typeof(CommandResponseMessage<EmptyResult>))]
[JsonSerializable(typeof(CommandResponseMessage<LocateNodesCommandResult>))]
[JsonSerializable(typeof(CommandResponseMessage<SubscribeCommandResult>))]
[JsonSerializable(typeof(EventMessage<FetchErrorEventArgs>))]
[JsonSerializable(typeof(EventMessage<RealmInfo>))]
[JsonSerializable(typeof(BluetoothManufacturerData))]
[JsonSerializable(typeof(HandleRequestDevicePromptCommandParameters))]
[JsonSerializable(typeof(ScanRecord))]
[JsonSerializable(typeof(SimulateAdapterCommandParameters))]
[JsonSerializable(typeof(SimulateAdvertisementCommandParameters))]
[JsonSerializable(typeof(SimulatePreConnectedPeripheralCommandParameters))]
[JsonSerializable(typeof(Browser.CloseCommandParameters), TypeInfoPropertyName = "BrowserCloseCommandParameters")]
[JsonSerializable(typeof(BrowsingContext.CloseCommandParameters), TypeInfoPropertyName = "BrowsingContextCloseCommandParameters")]
[JsonSerializable(typeof(CreateUserContextCommandParameters))]
[JsonSerializable(typeof(GetClientWindowsCommandParameters))]
[JsonSerializable(typeof(GetUserContextsCommandParameters))]
[JsonSerializable(typeof(RemoveUserContextCommandParameters))]
[JsonSerializable(typeof(SetClientWindowStateCommandParameters))]
[JsonSerializable(typeof(ActivateCommandParameters))]
[JsonSerializable(typeof(CaptureScreenshotCommandParameters))]
[JsonSerializable(typeof(CreateCommandParameters))]
[JsonSerializable(typeof(GetTreeCommandParameters))]
[JsonSerializable(typeof(HandleUserPromptCommandParameters))]
[JsonSerializable(typeof(LocateNodesCommandParameters))]
[JsonSerializable(typeof(NavigateCommandParameters))]
[JsonSerializable(typeof(PrintCommandParameters))]
[JsonSerializable(typeof(ReloadCommandParameters))]
[JsonSerializable(typeof(SetViewportCommandParameters))]
[JsonSerializable(typeof(TraverseHistoryCommandParameters))]
[JsonSerializable(typeof(ElementOrigin))]
[JsonSerializable(typeof(KeyDownAction))]
[JsonSerializable(typeof(KeySourceActions))]
[JsonSerializable(typeof(NoneSourceActions))]
[JsonSerializable(typeof(Origin))]
[JsonSerializable(typeof(PerformActionsCommandParameters))]
[JsonSerializable(typeof(ReleaseActionsCommandParameters))]
[JsonSerializable(typeof(SetFilesCommandParameters))]
[JsonSerializable(typeof(AddInterceptCommandParameters))]
[JsonSerializable(typeof(ContinueRequestCommandParameters))]
[JsonSerializable(typeof(ContinueResponseCommandParameters))]
[JsonSerializable(typeof(ContinueWithAuthCommandParameters))]
[JsonSerializable(typeof(FailRequestCommandParameters))]
[JsonSerializable(typeof(ProvideResponseCommandParameters))]
[JsonSerializable(typeof(RemoveInterceptCommandParameters))]
[JsonSerializable(typeof(SetCacheBehaviorCommandParameters))]
[JsonSerializable(typeof(SetPermissionCommandParameters))]
[JsonSerializable(typeof(AddPreloadScriptCommandParameters))]
[JsonSerializable(typeof(CallFunctionCommandParameters))]
[JsonSerializable(typeof(DisownCommandParameters))]
[JsonSerializable(typeof(EvaluateCommandParameters))]
[JsonSerializable(typeof(GetRealmsCommandParameters))]
[JsonSerializable(typeof(RemovePreloadScriptCommandParameters))]
[JsonSerializable(typeof(StatusCommandParameters))]
[JsonSerializable(typeof(NewCommandParameters))]
[JsonSerializable(typeof(SubscribeCommandParameters))]
[JsonSerializable(typeof(UnsubscribeCommandParameters))]
[JsonSerializable(typeof(EndCommandParameters))]
[JsonSerializable(typeof(GetCookiesCommandParameters))]
[JsonSerializable(typeof(SetCookieCommandParameters))]
[JsonSerializable(typeof(DeleteCookiesCommandParameters))]
[JsonSerializable(typeof(UnsubscribeByAttributesCommandParameters))]
[JsonSerializable(typeof(UnsubscribeByIdsCommandParameters))]
[JsonSerializable(typeof(IEnumerable<LocalValue>))]
public partial class JsonContext : JsonSerializerContext;